# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c-s.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tc-s.proto\x12\x04grpc\"%\n\x07request\x12\x0c\n\x04url1\x18\x01 \x01(\t\x12\x0c\n\x04url2\x18\x02 \x01(\t\"\x17\n\x08response\x12\x0b\n\x03\x61ns\x18\x01 \x01(\t2:\n\nChatServer\x12,\n\x0bSendRequest\x12\r.grpc.request\x1a\x0e.grpc.responseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['request']
_RESPONSE = DESCRIPTOR.message_types_by_name['response']
request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'c_s_pb2'
  # @@protoc_insertion_point(class_scope:grpc.request)
  })
_sym_db.RegisterMessage(request)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'c_s_pb2'
  # @@protoc_insertion_point(class_scope:grpc.response)
  })
_sym_db.RegisterMessage(response)

_CHATSERVER = DESCRIPTOR.services_by_name['ChatServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=19
  _REQUEST._serialized_end=56
  _RESPONSE._serialized_start=58
  _RESPONSE._serialized_end=81
  _CHATSERVER._serialized_start=83
  _CHATSERVER._serialized_end=141
# @@protoc_insertion_point(module_scope)
